/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SUPER_FINAL_PROJECT;

import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author meghana
 */
public class FriendFrame extends javax.swing.JFrame {
    
    Object[] items1, items2, items3;
    private Component frame;
    private int cid;
    /**
     * Creates new form FriendFrame
     */
    public FriendFrame(int track) throws SQLException {
               
        this.items1 = new Object[]{new Integer(0),new String(),new String()};
        this.items2 = new Object[]{new Integer(0),new String(),new String()};
        this.items3 = new Object[]{new Integer(0),new Integer(0), new String(),new String()};
        
        cid=track;
        
        new DB_Project(track);
                      
        initComponents();
        
        //set MyProfile details
        setMyProfileDetails();
             
        //set MyFriends details
         ArrayList<Integer> friends=DB_Project.returnFriends();
         addFriendItems(friends);
         
         //set MyReviews details
         ArrayList<Integer> tids=DB_Project.returnTids();
         setMyReviewsDetails(tids);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void setMyProfileDetails(){
        
        id_op_jLabel.setText(DB_Project.details[0]);
        name_op_jLabel.setText(DB_Project.details[1]);
        address_op_jLabel.setText(DB_Project.details[2]);
        userName_op_jLabel.setText(DB_Project.details[3]);
        wallet_op_jLabel.setText(DB_Project.details[4]);
        dob_op_jLabel.setText(DB_Project.details[5]);
        
    }
    
    private void addFriendItems(ArrayList<Integer> friends) throws SQLException
    
    {
        int i; ResultSet res;
             
        DefaultTableModel tb=(DefaultTableModel) jTable6.getModel();
        
              for(i=0;i<friends.size();i++)
            {  
                res = DB_Project.returnFriendDetails(friends.get(i));
                
                while(res.next())
                {
                    items1[0]=res.getInt("custid");
                    items1[1]=res.getString("custname");
                    items1[2]=res.getString("username");
                            
                    tb.addRow(items1);    
                 }
            }      
        
    }// end of addFriendItems
    
    public void setMyReviewsDetails(ArrayList<Integer> tids) throws SQLException{
        
         int i; ResultSet res;
             
        DefaultTableModel tb=(DefaultTableModel) jTable8.getModel();
        
              for(i=0;i<tids.size();i=i+2)
            {  
                res = DB_Project.returnReviews(tids.get(i), tids.get(i+1));
                
                while(res.next())
                {
                    items3[0]=res.getInt("tid");
                    items3[0]=res.getInt("pid");
                    items3[1]=res.getString("modelname");
                    items3[2]=res.getString("prodReview");
                            
                    tb.addRow(items3);    
                 }
            }     
        
        
    }// end of setMyReviewsDetails

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        viewjPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        search_jLabel = new javax.swing.JLabel();
        search_jTextField = new javax.swing.JTextField();
        search_jButton = new javax.swing.JButton();
        addFriend_jButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        myProfilejPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        id_jLabel = new javax.swing.JLabel();
        name_jLabel = new javax.swing.JLabel();
        address_jLabel = new javax.swing.JLabel();
        userName_jLabel = new javax.swing.JLabel();
        wallet_jLabel = new javax.swing.JLabel();
        dob_jLabel = new javax.swing.JLabel();
        id_op_jLabel = new javax.swing.JLabel();
        name_op_jLabel = new javax.swing.JLabel();
        address_op_jLabel = new javax.swing.JLabel();
        userName_op_jLabel = new javax.swing.JLabel();
        wallet_op_jLabel = new javax.swing.JLabel();
        dob_op_jLabel = new javax.swing.JLabel();
        changePassword_jButton = new javax.swing.JButton();
        addToWallet_jButton = new javax.swing.JButton();
        changeUserName_jButton = new javax.swing.JButton();
        myFriendsjPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        viewFriend_jButton = new javax.swing.JButton();
        deleteFriend_jButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        search_jLabel.setText("Search :");

        search_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_jTextFieldActionPerformed(evt);
            }
        });

        search_jButton.setText("Go");
        search_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(search_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_jLabel)
                    .addComponent(search_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_jButton))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        addFriend_jButton.setText("Add Friend");
        addFriend_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFriend_jButtonActionPerformed(evt);
            }
        });

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "User ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable7);
        if (jTable7.getColumnModel().getColumnCount() > 0) {
            jTable7.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout viewjPanelLayout = new javax.swing.GroupLayout(viewjPanel);
        viewjPanel.setLayout(viewjPanelLayout);
        viewjPanelLayout.setHorizontalGroup(
            viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewjPanelLayout.createSequentialGroup()
                .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewjPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewjPanelLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(addFriend_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(viewjPanelLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(83, Short.MAX_VALUE)))
        );
        viewjPanelLayout.setVerticalGroup(
            viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewjPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(addFriend_jButton)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(viewjPanelLayout.createSequentialGroup()
                    .addGap(140, 140, 140)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(92, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Add Friend", viewjPanel);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "My Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12)))); // NOI18N

        id_jLabel.setText("ID :");

        name_jLabel.setText("Name :");

        address_jLabel.setText("Address :");

        userName_jLabel.setText("User Name :");

        wallet_jLabel.setText("Wallet :");

        dob_jLabel.setText("Date of Birth :");

        id_op_jLabel.setText("jLabel1");

        name_op_jLabel.setText("jLabel2");

        address_op_jLabel.setText("jLabel3");

        userName_op_jLabel.setText("jLabel4");

        wallet_op_jLabel.setText("jLabel5");

        dob_op_jLabel.setText("jLabel6");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dob_jLabel)
                    .addComponent(userName_jLabel)
                    .addComponent(id_jLabel)
                    .addComponent(address_jLabel)
                    .addComponent(name_jLabel)
                    .addComponent(wallet_jLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_op_jLabel)
                    .addComponent(name_op_jLabel)
                    .addComponent(address_op_jLabel)
                    .addComponent(userName_op_jLabel)
                    .addComponent(wallet_op_jLabel)
                    .addComponent(dob_op_jLabel))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_jLabel)
                    .addComponent(id_op_jLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_jLabel)
                    .addComponent(name_op_jLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address_jLabel)
                    .addComponent(address_op_jLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userName_jLabel)
                    .addComponent(userName_op_jLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wallet_jLabel)
                    .addComponent(wallet_op_jLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dob_jLabel)
                    .addComponent(dob_op_jLabel))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        changePassword_jButton.setText("Change Password");
        changePassword_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassword_jButtonActionPerformed(evt);
            }
        });

        addToWallet_jButton.setText("Add to Wallet");
        addToWallet_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToWallet_jButtonActionPerformed(evt);
            }
        });

        changeUserName_jButton.setText("Change User Name");
        changeUserName_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUserName_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout myProfilejPanelLayout = new javax.swing.GroupLayout(myProfilejPanel);
        myProfilejPanel.setLayout(myProfilejPanelLayout);
        myProfilejPanelLayout.setHorizontalGroup(
            myProfilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myProfilejPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(myProfilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(changePassword_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addToWallet_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changeUserName_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        myProfilejPanelLayout.setVerticalGroup(
            myProfilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myProfilejPanelLayout.createSequentialGroup()
                .addGroup(myProfilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myProfilejPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(myProfilejPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(changeUserName_jButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changePassword_jButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addToWallet_jButton)))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("My Profile", myProfilejPanel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 817, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "User ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable6);
        if (jTable6.getColumnModel().getColumnCount() > 0) {
            jTable6.getColumnModel().getColumn(0).setResizable(false);
            jTable6.getColumnModel().getColumn(0).setHeaderValue("ID");
        }

        viewFriend_jButton.setText("View Friend");
        viewFriend_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFriend_jButtonActionPerformed(evt);
            }
        });

        deleteFriend_jButton.setText("Delete Friend");
        deleteFriend_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFriend_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout myFriendsjPanelLayout = new javax.swing.GroupLayout(myFriendsjPanel);
        myFriendsjPanel.setLayout(myFriendsjPanelLayout);
        myFriendsjPanelLayout.setHorizontalGroup(
            myFriendsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myFriendsjPanelLayout.createSequentialGroup()
                .addGroup(myFriendsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myFriendsjPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(myFriendsjPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(myFriendsjPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(viewFriend_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(deleteFriend_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        myFriendsjPanelLayout.setVerticalGroup(
            myFriendsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myFriendsjPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(myFriendsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewFriend_jButton)
                    .addComponent(deleteFriend_jButton))
                .addGap(758, 758, 758)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("My Friends", myFriendsjPanel);

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TID", "PID", "Product", "Review"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable8);
        if (jTable8.getColumnModel().getColumnCount() > 0) {
            jTable8.getColumnModel().getColumn(0).setResizable(false);
        }

        jButton3.setText("Add/Edit Review");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton3)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel4);

        jButton1.setText("<<Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton1)
                        .addGap(54, 54, 54)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_jTextFieldActionPerformed

    private void search_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_jButtonActionPerformed
        // TODO add your handling code here:
        String token = search_jTextField.getText();
        String[] details = DB_Project.returnPotentialFriend(token);
        
        DefaultTableModel tb=(DefaultTableModel) jTable7.getModel();
        
        if(details==null) JOptionPane.showMessageDialog(frame, "User does not Exist.");
        else{
        items2[0]=details[0];
        items2[1]=details[1];
        items2[2]=details[2];
        tb.addRow(items2);    
        }
    }//GEN-LAST:event_search_jButtonActionPerformed

    private void changeUserName_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUserName_jButtonActionPerformed
        // TODO add your handling code here:
        String newUserName = JOptionPane.showInputDialog("Enter your new User Name :");
        userName_op_jLabel.setText(newUserName);
        DB_Project.changeUserName(newUserName);
        JOptionPane.showMessageDialog(null,"UserName change was Successful.","Confirmation",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_changeUserName_jButtonActionPerformed

    private void changePassword_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassword_jButtonActionPerformed
        // TODO add your handling code here:
        int flag=-1;
        
        JPasswordField field1 = new JPasswordField(10);
        JPasswordField field2 = new JPasswordField(10);
      
        Object[] fields = {
            "Old Password", field1,
            "New Password", field2
        };
        int value = JOptionPane.showConfirmDialog(frame, fields, "Enter text", JOptionPane.OK_CANCEL_OPTION);
        if (value == JOptionPane.OK_OPTION)
        {
            // OK was pressed
            String oldPassword = field1.getText();
            char[] newPassword = field2.getPassword();
            // handle them
            flag = DB_Project.changePassword(oldPassword, newPassword);
        }
        
        if(flag==1) JOptionPane.showMessageDialog(null,"Password change was Successful.","Confirmation",JOptionPane.INFORMATION_MESSAGE);
        else        JOptionPane.showMessageDialog(null,"Password change was Unsuccessful.","Confirmation",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_changePassword_jButtonActionPerformed

    private void addToWallet_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToWallet_jButtonActionPerformed
        // TODO add your handling code here:
        String newAdd = JOptionPane.showInputDialog("Enter amount to be Added :");
        int newWalletAmount = DB_Project.addWallet(newAdd);
        wallet_op_jLabel.setText(Integer.toString(newWalletAmount));
        JOptionPane.showMessageDialog(null,"Wallet Addition was Successful.","Confirmation",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_addToWallet_jButtonActionPerformed

    private void deleteFriend_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFriend_jButtonActionPerformed
        // TODO add your handling code here:
       
        DefaultTableModel tb=(DefaultTableModel) jTable6.getModel();
        int row = jTable6.getSelectedRow();
        DB_Project.deleteFriend(Integer.parseInt((tb.getValueAt(row, 0)).toString()));
        tb.removeRow(row);
              
    
    }//GEN-LAST:event_deleteFriend_jButtonActionPerformed

    private void viewFriend_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFriend_jButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb=(DefaultTableModel) jTable6.getModel();
        int row = jTable6.getSelectedRow();
        String[] details = DB_Project.viewFriend(Integer.parseInt((tb.getValueAt(row, 0)).toString()));
              
        Object[] fields = {
            "User ID : "+details[0],
            "Name : "+ details[1],
            "Address : "+ details[2],
            "User Name : "+ details[3],
            "Date of Birth : "+ details[4]
        };
        JOptionPane.showMessageDialog(frame, fields);
        
  
    }//GEN-LAST:event_viewFriend_jButtonActionPerformed

    private void addFriend_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFriend_jButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb=(DefaultTableModel) jTable7.getModel();
        int row = jTable7.getSelectedRow();
        int flag = DB_Project.checkFriend(Integer.parseInt((tb.getValueAt(row, 0)).toString()));
        if(flag==1) JOptionPane.showMessageDialog(frame, "Already in your friend List.");
        else 
        {
        DB_Project.addFriend(Integer.parseInt((tb.getValueAt(row, 0)).toString()));
        JOptionPane.showMessageDialog(frame, "Friend Added Successfully.");
        
        int i; ResultSet res;
             
        DefaultTableModel tb2=(DefaultTableModel) jTable6.getModel();
        res = DB_Project.returnFriendDetails(Integer.parseInt((tb.getValueAt(row, 0)).toString()));
                
            try {
                while(res.next())
                {
                    items1[0]=res.getInt("custid");
                    items1[1]=res.getString("custname");
                    items1[2]=res.getString("username");
                    
                    tb2.addRow(items1);
                }
            } catch (SQLException ex) {
                Logger.getLogger(FriendFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            }      
        
        
    }//GEN-LAST:event_addFriend_jButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Login l=new Login();
l.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);
MainFrame m=new MainFrame(cid);
m.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String review = JOptionPane.showInputDialog("Enter your review within 140 characters : ");
        
        DefaultTableModel tb=(DefaultTableModel) jTable8.getModel();
        int row = jTable8.getSelectedRow();
        DB_Project.updateReview(Integer.parseInt((tb.getValueAt(row, 0)).toString()),Integer.parseInt((tb.getValueAt(row, 1)).toString()), review);

        jTable8.setValueAt(review, row, 2);
        JOptionPane.showMessageDialog(null,"Review Update was Successful.","Confirmation",JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FriendFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FriendFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FriendFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FriendFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FriendFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FriendFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFriend_jButton;
    private javax.swing.JButton addToWallet_jButton;
    private javax.swing.JLabel address_jLabel;
    private javax.swing.JLabel address_op_jLabel;
    private javax.swing.JButton changePassword_jButton;
    private javax.swing.JButton changeUserName_jButton;
    private javax.swing.JButton deleteFriend_jButton;
    private javax.swing.JLabel dob_jLabel;
    private javax.swing.JLabel dob_op_jLabel;
    private javax.swing.JLabel id_jLabel;
    private javax.swing.JLabel id_op_jLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JPanel myFriendsjPanel;
    private javax.swing.JPanel myProfilejPanel;
    private javax.swing.JLabel name_jLabel;
    private javax.swing.JLabel name_op_jLabel;
    private javax.swing.JButton search_jButton;
    private javax.swing.JLabel search_jLabel;
    private javax.swing.JTextField search_jTextField;
    private javax.swing.JLabel userName_jLabel;
    private javax.swing.JLabel userName_op_jLabel;
    private javax.swing.JButton viewFriend_jButton;
    private javax.swing.JPanel viewjPanel;
    private javax.swing.JLabel wallet_jLabel;
    private javax.swing.JLabel wallet_op_jLabel;
    // End of variables declaration//GEN-END:variables

}
